### ISSUE TITLE
Unit test failure in `TestRegisteredHooks.test_hooks`

### ISSUE THREAD

**Issue by fnordahl** [openstack-charmers/charm-octavia#1]
I am failing to see why this is blowing up, probably something obvious I have missed. May I ask if you would be able to shed some light on what is going on @ajkavanagh ?
```
$ tox
pep8 installed: attrs==18.2.0,certifi==2018.8.24,chardet==3.0.4,charmhelpers==0.19.2,charms.openstack==0.0.1.dev1,charms.reactive==1.1.2,cliff==2.13.0,cmd2==0.9.4,colorama==0.3.9,coverage==4.5.1,extras==1.0.0,fixtures==3.0.0,flake8==2.4.1,future==0.16.0,idna==2.7,Jinja2==2.10,linecache2==1.0.0,MarkupSafe==1.0,mccabe==0.3.1,mock==2.0.0,netaddr==0.7.19,nose==1.3.7,os-testr==1.0.0,pbr==4.3.0,pep8==1.7.1,pkg-resources==0.0.0,prettytable==0.7.2,pyaml==17.12.1,pyflakes==0.8.1,pyparsing==2.2.2,pyperclip==1.7.0,python-mimeparse==1.6.0,python-subunit==1.3.0,PyYAML==3.13,requests==2.19.1,six==1.11.0,stestr==2.1.1,stevedore==1.29.0,Tempita==0.5.2,testtools==2.3.0,traceback2==1.4.0,unittest2==1.1.0,urllib3==1.23,voluptuous==0.11.5,wcwidth==0.1.7
pep8 runtests: PYTHONHASHSEED='0'
pep8 runtests: commands[0] | flake8 src unit_tests
py3 installed: attrs==18.2.0,certifi==2018.8.24,chardet==3.0.4,charmhelpers==0.19.2,charms.openstack==0.0.1.dev1,charms.reactive==1.1.2,cliff==2.13.0,cmd2==0.9.4,colorama==0.3.9,coverage==4.5.1,extras==1.0.0,fixtures==3.0.0,flake8==2.4.1,future==0.16.0,idna==2.7,Jinja2==2.10,linecache2==1.0.0,MarkupSafe==1.0,mccabe==0.3.1,mock==2.0.0,netaddr==0.7.19,nose==1.3.7,os-testr==1.0.0,pbr==4.3.0,pep8==1.7.1,pkg-resources==0.0.0,prettytable==0.7.2,pyaml==17.12.1,pyflakes==0.8.1,pyparsing==2.2.2,pyperclip==1.7.0,python-mimeparse==1.6.0,python-subunit==1.3.0,PyYAML==3.13,requests==2.19.1,six==1.11.0,stestr==2.1.1,stevedore==1.29.0,Tempita==0.5.2,testtools==2.3.0,traceback2==1.4.0,unittest2==1.1.0,urllib3==1.23,voluptuous==0.11.5,wcwidth==0.1.7
py3 runtests: PYTHONHASHSEED='0'
py3 runtests: commands[0] | ostestr
{1} unit_tests.test_lib_charm_openstack_octavia.TestOctaviaCharm.test_get_amqp_credentials [0.001605s] ... ok
{0} unit_tests.test_octavia_handlers.TestRender.test_render [0.002370s] ... ok
{2} unit_tests.test_lib_charm_openstack_octavia.TestOctaviaCharm.test_get_database_setup [0.002211s] ... ok
{3} unit_tests.test_octavia_handlers.TestRegisteredHooks.test_hooks [0.001602s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "/home/frode/Projects/OpenStack/charm-octavia/unit_tests/test_octavia_handlers.py", line 49, in test_hooks'
    b'    self.registered_hooks_test_helper(handlers, hook_set, defaults)'
    b'  File "/home/frode/Projects/OpenStack/charm-octavia/.tox/py3/lib/python3.6/site-packages/charms_openstack/test_utils.py", line 230, in registered_hooks_test_helper'
    b'    "for function \'{}\'".format(f))'
    b'  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual'
    b'    assertion_func(first, second, msg=msg)'
    b'  File "/usr/lib/python3.6/unittest/case.py", line 1028, in assertListEqual'
    b'    self.assertSequenceEqual(list1, list2, msg, seq_type=list)'
    b'  File "/usr/lib/python3.6/unittest/case.py", line 1010, in assertSequenceEqual'
    b'    self.fail(msg)'
    b'  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail'
    b'    raise self.failureException(msg)'
    b"AssertionError: Lists differ: ['config.rendered'] != ['.', 'c', 'd', 'd', 'e', 'e', 'e', 'f', 'g', 'i', 'n', 'n', 'o', 'r', 'r']"
    b''
    b'First differing element 0:'
    b"'config.rendered'"
    b"'.'"
    b''
    b'Second list contains 14 additional elements.'
    b'First extra element 1:'
    b"'c'"
    b''
    b"- ['config.rendered']"
    b"+ ['.', 'c', 'd', 'd', 'e', 'e', 'e', 'f', 'g', 'i', 'n', 'n', 'o', 'r', 'r'] : for function 'init_db'"
    b''

==============================
Failed 1 tests - output below:
==============================

unit_tests.test_octavia_handlers.TestRegisteredHooks.test_hooks
---------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "/home/frode/Projects/OpenStack/charm-octavia/unit_tests/test_octavia_handlers.py", line 49, in test_hooks'
    b'    self.registered_hooks_test_helper(handlers, hook_set, defaults)'
    b'  File "/home/frode/Projects/OpenStack/charm-octavia/.tox/py3/lib/python3.6/site-packages/charms_openstack/test_utils.py", line 230, in registered_hooks_test_helper'
    b'    "for function \'{}\'".format(f))'
    b'  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual'
    b'    assertion_func(first, second, msg=msg)'
    b'  File "/usr/lib/python3.6/unittest/case.py", line 1028, in assertListEqual'
    b'    self.assertSequenceEqual(list1, list2, msg, seq_type=list)'
    b'  File "/usr/lib/python3.6/unittest/case.py", line 1010, in assertSequenceEqual'
    b'    self.fail(msg)'
    b'  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail'
    b'    raise self.failureException(msg)'
    b"AssertionError: Lists differ: ['config.rendered'] != ['.', 'c', 'd', 'd', 'e', 'e', 'e', 'f', 'g', 'i', 'n', 'n', 'o', 'r', 'r']"
    b''
    b'First differing element 0:'
    b"'config.rendered'"
    b"'.'"
    b''
    b'Second list contains 14 additional elements.'
    b'First extra element 1:'
    b"'c'"
    b''
    b"- ['config.rendered']"
    b"+ ['.', 'c', 'd', 'd', 'e', 'e', 'e', 'f', 'g', 'i', 'n', 'n', 'o', 'r', 'r'] : for function 'init_db'"
    b''


======
Totals
======
Ran: 4 tests in 0.1932 sec.
 - Passed: 3
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 1
Sum of execute time for each test: 0.0078 sec.

==============
Worker Balance
==============
 - Worker 0 (1 tests) => 0:00:00.002370
 - Worker 1 (1 tests) => 0:00:00.001605
 - Worker 2 (1 tests) => 0:00:00.002211
 - Worker 3 (1 tests) => 0:00:00.001602

Slowest Tests:
Test id                                                                                 Runtime (s)
--------------------------------------------------------------------------------------  -----------
unit_tests.test_octavia_handlers.TestRender.test_render                                 0.002
unit_tests.test_lib_charm_openstack_octavia.TestOctaviaCharm.test_get_database_setup    0.002
unit_tests.test_lib_charm_openstack_octavia.TestOctaviaCharm.test_get_amqp_credentials  0.002
unit_tests.test_octavia_handlers.TestRegisteredHooks.test_hooks                         0.002
ERROR: InvocationError: '/home/frode/Projects/OpenStack/charm-octavia/.tox/py3/bin/ostestr'
____________________________________________________________________ summary _____________________________________________________________________
  pep8: commands succeeded
ERROR:   py3: commands failed
```

**Comment by fnordahl** [comment]
Fixed in commit 87b96027c462dfef500903986190139ebc653345
